FROM python:3.8-buster

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade setuptools

RUN python3 -m pip install nvflare==2.4.0

COPY requirements.txt /workspace/requirements.txt

RUN python3 -m pip install -r /workspace/requirements.txt

WORKDIR /workspace/

ENV PYTHONPATH=$PYTHONPATH:/workspace/app/code/
ENV NVFLARE_POC_WORKSPACE=/workspace/poc-workspace

# Default command
CMD ["/bin/bash"]
